backend:
  container_name: ROSA-API-BACKEND
  build: .
  command: python3 -u app.py
  ports:
    - "8080:8080"
  volumes:
    - .:/opt/projetos/dev/api
  links:
    - db
db:
  image: mongo:latest
  container_name: MONGO-API
  ports:
    - "27017:27017"
  volumes:
    - .:/opt/projetos/dev/api/data   
 
